### ISSUE TITLE
global chefignore, or useful default

### ISSUE THREAD

**Issue by petere** [berkshelf/ridley#300]
It would be useful to be able to have a global `chefignore` file, under `~/.chefignore` or perhaps `~/.chef/chefignore` or whatever.

Alternatively, ridley could have a more useful default set of ignores, so that the need for having a manual `chefignore` at all might go away.

First, I need to ignore editor temporary files.  This is not something that the cookbook determines, but my environment, so it doesn't belong in the cookbook's `chefignore`.  This is super-annoying, because it basically means you can't keep editing the cookbook while test-kitchen runs (without changing the editor configuration).

Second, because of the way I manage my repositories, some files under `.git` are relative symlinks.  Apparently, ridley copies the entire cookbook to a staging directory before uploading, and that breaks the symlinks.  I want to globally ignore the `.git` directory, or alternatively VCS directories should be ignored by default.

**Comment by reset** [comment]
@petere I think that this is a good idea with good intentions and was something that I briefly considered a while back. There are two reasons it's not included in Ridley or Berkshelf:

* This would actually belong in Chef itself. Ridley/Berkshelf/Knife and other tools could leverage the global ignore file if this was a standard among the tools.
* I think this feature could lead down a road of confusion because the contents of the packaged artifact could mutate depending on which node was performing the packaging even though the exact same arguments are passed to the CLI.

If you'd like to see this added I would recommend opening up a discussion on the Chef issue tracker instead of here. If it gets added then I'll update Ridley to leverage it ;).
