### ISSUE TITLE
Ridley -> Chef-Guard -> Supermarket schema is not working

### ISSUE THREAD

**Issue by iroller** [berkshelf/ridley#310]
It's more of a question, not an issue.

I have chef-guard installed with [publishcookbook](https://github.com/xanzy/chef-guard/blob/54728b35b30b2fc28d91ec47a44ec2f3bd5a7af0/supermarket.go#L39) option enabled and when I'm uploading a cookbook using knife it gets uploaded to supermarket by chef-guard just fine.

However when I'm uploading the same cookbook with ridley I'm getting the following error from supermarket:
```
ERROR: Failed to upload mycookbook to the Supermarket:
Multipart POST part 'tarball' must contain a metadata.json entry.;
Multipart POST part 'tarball' must contain a non-empty README.
```

Since it works fine in the first case I guess it's something to do with how ridley upload is different from knife upload?

I'd appreciate some pointers on where to look. And feel free to close the issue at any moment.

**Comment by lamont-granquist** [comment]
ridley upload most likely is doing a straight file upload of whatever you have.   chef-guard is doing extra work to generate a metadata.json for you and create a (presumably zero-length) README file or something.

feels like ridley is working by design, and this additional framework is part of the app and not this library -- and berks itself must have similar code.

even if you argued that ridley should make it easy for app developers, this is just a low priority that we'll never spend the time to implement it ourselves, so it falls into the "PRs welcome!" bucket at best.

as this was just an informational request, i think that's the best i can offer.
